name: SwiftAPIBreakage

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  buildAndCheckAPIBreakage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - uses: ltetzlaff/swift-api-diff@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
