name: SwiftTest

on: [push]

jobs:
  buildAndTestMacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
